# Generated by Django 2.0.7 on 2018-08-30 07:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Metadata'),
        ),
    ]
