# Generated by Django 2.0.6 on 2018-06-06 09:15

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created',
                 models.DateTimeField(
                     auto_now_add=True, verbose_name='Created')),
                ('modified',
                 models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('ona_pk',
                 models.PositiveIntegerField(
                     db_index=True,
                     unique=True,
                     verbose_name='Onadata Primary Key')),
                ('json',
                 django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('deleted_at',
                 models.DateTimeField(
                     default=None, null=True, verbose_name='Deleted at')),
                ('last_updated',
                 models.DateTimeField(
                     blank=True,
                     default=None,
                     null=True,
                     verbose_name='Last Updated')),
                ('user',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.PROTECT,
                     to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['ona_pk', 'deleted_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created',
                 models.DateTimeField(
                     auto_now_add=True, verbose_name='Created')),
                ('modified',
                 models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('ona_pk',
                 models.PositiveIntegerField(
                     db_index=True,
                     unique=True,
                     verbose_name='Onadata Primary Key')),
                ('organization',
                 models.PositiveIntegerField(
                     blank=True,
                     default=None,
                     null=True,
                     verbose_name='Organization ID')),
                ('name', models.CharField(max_length=255)),
                ('deleted_at',
                 models.DateTimeField(
                     default=None, null=True, verbose_name='Deleted at')),
                ('last_updated',
                 models.DateTimeField(
                     blank=True,
                     default=None,
                     null=True,
                     verbose_name='Last Updated')),
            ],
            options={
                'ordering': ['name', 'ona_pk'],
            },
        ),
        migrations.CreateModel(
            name='XForm',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('created',
                 models.DateTimeField(
                     auto_now_add=True, verbose_name='Created')),
                ('modified',
                 models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('ona_pk',
                 models.PositiveIntegerField(
                     db_index=True,
                     unique=True,
                     verbose_name='Onadata Primary Key')),
                ('project_id',
                 models.PositiveIntegerField(
                     db_index=True, verbose_name='Project ID')),
                ('title',
                 models.CharField(
                     editable=False, max_length=255, verbose_name='Title')),
                ('id_string',
                 models.SlugField(
                     editable=False, max_length=100,
                     verbose_name='ID String')),
                ('deleted_at',
                 models.DateTimeField(
                     default=None, null=True, verbose_name='Deleted at')),
                ('last_updated',
                 models.DateTimeField(
                     blank=True,
                     default=None,
                     null=True,
                     verbose_name='Last Updated')),
            ],
            options={
                'ordering': ['title', 'id_string'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='xform',
            unique_together={('project_id', 'id_string')},
        ),
        migrations.AddField(
            model_name='instance',
            name='xform',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to='ona.XForm'),
        ),
    ]
