# Generated by Django 2.0.7 on 2018-07-20 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='deleted_at',
            field=models.DateTimeField(
                blank=True, default=None, null=True,
                verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='project',
            name='deleted_at',
            field=models.DateTimeField(
                blank=True, default=None, null=True,
                verbose_name='Deleted at'),
        ),
        migrations.AlterField(
            model_name='xform',
            name='deleted_at',
            field=models.DateTimeField(
                blank=True, default=None, null=True,
                verbose_name='Deleted at'),
        ),
    ]
