# Generated by Django 2.0.7 on 2018-08-16 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ona', '0002_auto_20180720_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='xform',
            name='kaznet_project',
            field=models.ForeignKey(blank=True, help_text='This references the Kaznet Project.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ona.Project', verbose_name='Kaznet Project'),
        ),
        migrations.AlterField(
            model_name='xform',
            name='project_id',
            field=models.PositiveIntegerField(db_index=True, help_text='References the Project ID from Ona Data', verbose_name='Project ID'),
        ),
    ]
