# Generated by Django 2.0.8 on 2018-09-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ona', '0003_auto_20180816_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='xform',
            name='version',
            field=models.SlugField(
                default=None,
                editable=False,
                max_length=255,
                null=True,
                verbose_name='Version'),
        ),
    ]
