# Generated by Django 2.0.8 on 2018-09-13 12:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ona', '0004_xform_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='xform',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, verbose_name='Metadata'),
        ),
    ]
