# Generated by Django 2.0.9 on 2019-01-25 14:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ona', '0005_xform_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='json',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                default=dict, verbose_name='Data'),
        ),
    ]
